"""add user_id to user_tasks

Revision ID: bafe5bfb7951
Revises: eb49c3909d5e
Create Date: 2026-05-18 11:10:17.852501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bafe5bfb7951'
down_revision: Union[str, Sequence[str], None] = 'eb49c3909d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tasks', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('user_tasks_userid_fkey'), 'user_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'user_tasks', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_tasks', 'is_completed')
    op.drop_column('user_tasks', 'userid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tasks', sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_tasks', sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('user_tasks_userid_fkey'), 'user_tasks', 'user', ['userid'], ['id'], ondelete='CASCADE')
    op.drop_column('user_tasks', 'user_id')
    # ### end Alembic commands ###
